### ISSUE TITLE
k-way marginal selection methodology

### ISSUE THREAD

**Issue by bavent** [amazon-research/relaxed-adaptive-projection#2]
Hi, thanks for posting the repo alongside your paper! I’ve been putting together my own implementation of your algorithm, so now being able to dig through the original code is really enjoyable.

I’m trying to get a better grasp on the methodology used to select the k-way marginals and their corresponding consistent queries, particularly with regards to Figure 7 in the paper (where the available queries eventually become saturated).

My understanding was that the number of queries consistent with a workload would always increase as the size of the workload increases, so long as that size is less than the total number of distinct marginals: (#features choose k). However, taking datasets/adult.py as an example, I noticed that “large” marginals (ones whose features have a large number of categories) are being rejected at the following snippet
```
# generate k-ways with support smaller than the actual population
proj = [
            p
            for p in itertools.combinations(self.df.columns, k)
            if self._get_size_domain(p) <= total
]
```
which leads to mildly early saturation when k=3 and extremely early saturation when k=5.

I’m wondering why this `if self._get_size_domain(p) <= total` rejection criteria was added (e.g., is there a mathematical justification for why it should explicitly be smaller than the actual population, is it there purely to ease the computational load, etc.) and if there is any known effect on the experimental results if it is removed?

**Comment by AnkitSiva** [comment]
Hey Brendan! Thanks for posting this issue. Your understanding is right.
The rejection criteria was a simple heuristic to reduce computational load. If it's removed, I think the algorithm would display the same degradation in performance that increasing the workload has, holding all other hyper-parameters constant.
For 
I'll discuss this with the team and update this issue if we run an experiment to verify that hypothesis. You're also welcome to remove that line and let us know how it performs of course!

**Comment by bavent** [comment]
Thanks for the response Ankit! I'd be very interested to know the results of that experiment if you all do run it. I'd run it myself, but my computer is too weak to handle running it even without removing that line 😆
